platform :ios, '9.0'


use_frameworks!
inhibit_all_warnings!

swift_version = "4.0"

target 'Use_Desk_iOS_SDK_Example' do
    #pod 'Realm'
    
    #pod 'MBProgressHUD'
    #pod 'NYTPhotoViewer', '1.2.0'
    #pod 'ProgressHUD'
    #pod 'RCAudioPlayer'
    #pod 'Socket.IO-Client-Swift'
    #pod 'AFNetworking', '~> 3.1.0'
    #pod 'RCAudioPlayer'
    #pod 'NSDate-Escort'
    #pod 'NSDate+Helpers'
    pod 'Use_Desk_iOS_SDK', :path => '../'

  target 'Use_Desk_iOS_SDK_Tests' do
    inherit! :search_paths

  end
end


pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end

